// Code generated by counterfeiter. DO NOT EDIT.
package csibroker_fake

import (
	"sync"

	"code.cloudfoundry.org/csibroker/csibroker"
	"github.com/container-storage-interface/spec/lib/go/csi/v0"
	"github.com/pivotal-cf/brokerapi"
)

type FakeServicesRegistry struct {
	IdentityClientStub        func(serviceID string) (csi.IdentityClient, error)
	identityClientMutex       sync.RWMutex
	identityClientArgsForCall []struct {
		serviceID string
	}
	identityClientReturns struct {
		result1 csi.IdentityClient
		result2 error
	}
	identityClientReturnsOnCall map[int]struct {
		result1 csi.IdentityClient
		result2 error
	}
	ControllerClientStub        func(serviceID string) (csi.ControllerClient, error)
	controllerClientMutex       sync.RWMutex
	controllerClientArgsForCall []struct {
		serviceID string
	}
	controllerClientReturns struct {
		result1 csi.ControllerClient
		result2 error
	}
	controllerClientReturnsOnCall map[int]struct {
		result1 csi.ControllerClient
		result2 error
	}
	BrokerServicesStub        func() []brokerapi.Service
	brokerServicesMutex       sync.RWMutex
	brokerServicesArgsForCall []struct{}
	brokerServicesReturns     struct {
		result1 []brokerapi.Service
	}
	brokerServicesReturnsOnCall map[int]struct {
		result1 []brokerapi.Service
	}
	DriverNameStub        func(serviceID string) (string, error)
	driverNameMutex       sync.RWMutex
	driverNameArgsForCall []struct {
		serviceID string
	}
	driverNameReturns struct {
		result1 string
		result2 error
	}
	driverNameReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeServicesRegistry) IdentityClient(serviceID string) (csi.IdentityClient, error) {
	fake.identityClientMutex.Lock()
	ret, specificReturn := fake.identityClientReturnsOnCall[len(fake.identityClientArgsForCall)]
	fake.identityClientArgsForCall = append(fake.identityClientArgsForCall, struct {
		serviceID string
	}{serviceID})
	fake.recordInvocation("IdentityClient", []interface{}{serviceID})
	fake.identityClientMutex.Unlock()
	if fake.IdentityClientStub != nil {
		return fake.IdentityClientStub(serviceID)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.identityClientReturns.result1, fake.identityClientReturns.result2
}

func (fake *FakeServicesRegistry) IdentityClientCallCount() int {
	fake.identityClientMutex.RLock()
	defer fake.identityClientMutex.RUnlock()
	return len(fake.identityClientArgsForCall)
}

func (fake *FakeServicesRegistry) IdentityClientArgsForCall(i int) string {
	fake.identityClientMutex.RLock()
	defer fake.identityClientMutex.RUnlock()
	return fake.identityClientArgsForCall[i].serviceID
}

func (fake *FakeServicesRegistry) IdentityClientReturns(result1 csi.IdentityClient, result2 error) {
	fake.IdentityClientStub = nil
	fake.identityClientReturns = struct {
		result1 csi.IdentityClient
		result2 error
	}{result1, result2}
}

func (fake *FakeServicesRegistry) IdentityClientReturnsOnCall(i int, result1 csi.IdentityClient, result2 error) {
	fake.IdentityClientStub = nil
	if fake.identityClientReturnsOnCall == nil {
		fake.identityClientReturnsOnCall = make(map[int]struct {
			result1 csi.IdentityClient
			result2 error
		})
	}
	fake.identityClientReturnsOnCall[i] = struct {
		result1 csi.IdentityClient
		result2 error
	}{result1, result2}
}

func (fake *FakeServicesRegistry) ControllerClient(serviceID string) (csi.ControllerClient, error) {
	fake.controllerClientMutex.Lock()
	ret, specificReturn := fake.controllerClientReturnsOnCall[len(fake.controllerClientArgsForCall)]
	fake.controllerClientArgsForCall = append(fake.controllerClientArgsForCall, struct {
		serviceID string
	}{serviceID})
	fake.recordInvocation("ControllerClient", []interface{}{serviceID})
	fake.controllerClientMutex.Unlock()
	if fake.ControllerClientStub != nil {
		return fake.ControllerClientStub(serviceID)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.controllerClientReturns.result1, fake.controllerClientReturns.result2
}

func (fake *FakeServicesRegistry) ControllerClientCallCount() int {
	fake.controllerClientMutex.RLock()
	defer fake.controllerClientMutex.RUnlock()
	return len(fake.controllerClientArgsForCall)
}

func (fake *FakeServicesRegistry) ControllerClientArgsForCall(i int) string {
	fake.controllerClientMutex.RLock()
	defer fake.controllerClientMutex.RUnlock()
	return fake.controllerClientArgsForCall[i].serviceID
}

func (fake *FakeServicesRegistry) ControllerClientReturns(result1 csi.ControllerClient, result2 error) {
	fake.ControllerClientStub = nil
	fake.controllerClientReturns = struct {
		result1 csi.ControllerClient
		result2 error
	}{result1, result2}
}

func (fake *FakeServicesRegistry) ControllerClientReturnsOnCall(i int, result1 csi.ControllerClient, result2 error) {
	fake.ControllerClientStub = nil
	if fake.controllerClientReturnsOnCall == nil {
		fake.controllerClientReturnsOnCall = make(map[int]struct {
			result1 csi.ControllerClient
			result2 error
		})
	}
	fake.controllerClientReturnsOnCall[i] = struct {
		result1 csi.ControllerClient
		result2 error
	}{result1, result2}
}

func (fake *FakeServicesRegistry) BrokerServices() []brokerapi.Service {
	fake.brokerServicesMutex.Lock()
	ret, specificReturn := fake.brokerServicesReturnsOnCall[len(fake.brokerServicesArgsForCall)]
	fake.brokerServicesArgsForCall = append(fake.brokerServicesArgsForCall, struct{}{})
	fake.recordInvocation("BrokerServices", []interface{}{})
	fake.brokerServicesMutex.Unlock()
	if fake.BrokerServicesStub != nil {
		return fake.BrokerServicesStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.brokerServicesReturns.result1
}

func (fake *FakeServicesRegistry) BrokerServicesCallCount() int {
	fake.brokerServicesMutex.RLock()
	defer fake.brokerServicesMutex.RUnlock()
	return len(fake.brokerServicesArgsForCall)
}

func (fake *FakeServicesRegistry) BrokerServicesReturns(result1 []brokerapi.Service) {
	fake.BrokerServicesStub = nil
	fake.brokerServicesReturns = struct {
		result1 []brokerapi.Service
	}{result1}
}

func (fake *FakeServicesRegistry) BrokerServicesReturnsOnCall(i int, result1 []brokerapi.Service) {
	fake.BrokerServicesStub = nil
	if fake.brokerServicesReturnsOnCall == nil {
		fake.brokerServicesReturnsOnCall = make(map[int]struct {
			result1 []brokerapi.Service
		})
	}
	fake.brokerServicesReturnsOnCall[i] = struct {
		result1 []brokerapi.Service
	}{result1}
}

func (fake *FakeServicesRegistry) DriverName(serviceID string) (string, error) {
	fake.driverNameMutex.Lock()
	ret, specificReturn := fake.driverNameReturnsOnCall[len(fake.driverNameArgsForCall)]
	fake.driverNameArgsForCall = append(fake.driverNameArgsForCall, struct {
		serviceID string
	}{serviceID})
	fake.recordInvocation("DriverName", []interface{}{serviceID})
	fake.driverNameMutex.Unlock()
	if fake.DriverNameStub != nil {
		return fake.DriverNameStub(serviceID)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.driverNameReturns.result1, fake.driverNameReturns.result2
}

func (fake *FakeServicesRegistry) DriverNameCallCount() int {
	fake.driverNameMutex.RLock()
	defer fake.driverNameMutex.RUnlock()
	return len(fake.driverNameArgsForCall)
}

func (fake *FakeServicesRegistry) DriverNameArgsForCall(i int) string {
	fake.driverNameMutex.RLock()
	defer fake.driverNameMutex.RUnlock()
	return fake.driverNameArgsForCall[i].serviceID
}

func (fake *FakeServicesRegistry) DriverNameReturns(result1 string, result2 error) {
	fake.DriverNameStub = nil
	fake.driverNameReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeServicesRegistry) DriverNameReturnsOnCall(i int, result1 string, result2 error) {
	fake.DriverNameStub = nil
	if fake.driverNameReturnsOnCall == nil {
		fake.driverNameReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.driverNameReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeServicesRegistry) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.identityClientMutex.RLock()
	defer fake.identityClientMutex.RUnlock()
	fake.controllerClientMutex.RLock()
	defer fake.controllerClientMutex.RUnlock()
	fake.brokerServicesMutex.RLock()
	defer fake.brokerServicesMutex.RUnlock()
	fake.driverNameMutex.RLock()
	defer fake.driverNameMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeServicesRegistry) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ csibroker.ServicesRegistry = new(FakeServicesRegistry)
